# Generated by Django 4.1.1 on 2022-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blog_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
        migrations.AddField(
            model_name='about',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
