# Generated by Django 4.0.1 on 2022-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_social_facebook_alter_social_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Studied_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='workad_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
