# Generated by Django 4.1.1 on 2022-10-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_about_user_about_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
