# Generated by Django 4.1.1 on 2022-10-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_about_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
    ]
